version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: devfest-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../certbot/www:/var/www/certbot:ro
    networks:
      - app-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ../certbot/conf:/etc/letsencrypt:rw
      - ../certbot/www:/var/www/certbot:rw
    networks:
      - app-network

networks:
  app-network:
    driver: bridge