version: '3.8'

services:
  web:
    build:
      context: ..  # Your context, where the Dockerfile is located
      dockerfile: docker/Dockerfile
    container_name: devfest-web
    restart: unless-stopped
    ports:
      - "80:80"    # Expose port 80 for HTTP
      - "443:443"  # Expose port 443 for HTTPS
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
      - ../certbot/www:/var/www/certbot  # Directory for Certbot challenges
      - /etc/letsencrypt:/etc/letsencrypt  # Mount the Let's Encrypt certificates
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ../certbot/www:/var/www/certbot  # Directory for Certbot challenges
      - /etc/letsencrypt:/etc/letsencrypt  # Mount the Let's Encrypt certificates
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge
